#!/usr/bin/env perl
#
# Thousands of years ago...
#
use strict;
use warnings;

use Array::RealSpan;

my $point = defined $ARGV[0] ? shift : die "Usage: perl $0 0-1999.9~\n";

my $span = Array::RealSpan->new;
$span->set_range(   0,    1.2,  'iron age' );
$span->set_range(   1.2,  1.55, 'late bronze age' );
$span->set_range(   1.55, 2.1,  'middle bronze age' );
$span->set_range(   2.1,  3.3,  'early bronze age' );
$span->set_range(   3.3,  5,    'copper age' );
$span->set_range(   5,    9,    'neolithic' );
$span->set_range(   9,   10,    'mesolithic' );
$span->set_range(  10,   30,    'upper paleolithic' );
$span->set_range(  30,  100,    'middle paleolithic' );
$span->set_range( 100, 2000,    'lower paleolithic' );

print "$point thousand years ago is the ";
print $span->lookup($point), "\n"
    if $span->lookup($point);
